spring:
  application:
    name: demoserver
  profiles:
    active:
      default
  cloud:
    config:
      enabled: true

server:
  port: 8001

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/