#Default port is 8761
spring:
  application:
    name: eurekaserver

server:
  port: 8761

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
  server:
    waitTimeInMsWhenSyncEmpty: 30
  serviceUrl:
    defaultZone: http://localhost:8761
  
